# Generated by Django 4.2.11 on 2024-12-01 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('login', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=256)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
